CAPS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('superadmin/', include('superadmin.urls')),
    path('mentor/', include('mentor.urls')),
    path('volunteer/', include('volunteer.urls')),

    # path('accounts/', include('django.contrib.auth.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [

    # ----------------------------- Basic URLS ------------------------------------------->
    path('',views.index_func, name='index_url'),
    path('noaccess',views.unauthorized_func, name='unauthorized_access_url'),

    # ---------------------------- Login and logout urls --------------------------------->
    path('login/',views.loginfunc, name='login_url'),
    path('logout/',views.logoutfunc, name='logout_url'),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/pwd_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/pwd_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/pwd_reset_complete.html'), name='password_reset_complete'),      

    # ---------------------------- OTO booking urls -------------------------------------->
    path('otobooking/',views.oto_booking_func, name='oto_booking_url'),
    # Dont delete these urls .. it is back up for sending mail with encrypted link
    # path('otostudentfeedback/<slug:uidb64>/',views.oto_s_feedback_func, name='oto_s_feedback_url'),
    path('otostudentfeedback/<int:pkid>/',views.oto_s_feedback_func, name='oto_s_feedback_url'),

    # path('otofeedback/<slug:pk>', views.oto_feedback_func, name="otofeedback_url"),
    # path('otocompleted/<int:pk>', views.oto_completed_func, name="otofeedback_url"),

    # ----------------- ----------Group booking urls--------------------------------------->
    path('grpbooking/',views.grp_booking_func, name='grp_booking_url'),
    # path('groupfeedback/<slug:uidb64>/',views.grp_s_feedback_func, name='grp_s_feedback_url'), 
    path('groupfeedback/<int:pkid>/',views.grp_s_feedback_func, name='grp_s_feedback_url'),

    path('usersessionlist/',views.usersessionlistfunc, name='usersessionlist_url'),

    #  -------------------------Feedback anf tracing urls --------------------------------->
    # path('feedbackrequest/',views.feedback_request_func, name='feedback_request_url'),
    # path('otpconfirm/',views.otp_confirm_func, name='otp_confirm_url'),
    # path('feedback/',views.feedback_func, name='feedback'),

    path('feedbackrequest/', views.feedback_verification_func, name="feedback_verification_url"),
    path('feedbackotp/<int:pkid>', views.feedback_otp_func, name="feedback_otp_url"),
    path('feedbackgroupotp/<int:pkid>', views.feedback_otp_grp_func, name="feedback_otp_grp_url"),

    
    # path('otofeedback/',views.feedback, name='oto_feedback'),
]

accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.core.exceptions import ValidationError

from .managers import UserManager

import re
import datetime

from_date = datetime.datetime(2019, 10, 21)

to_date   = datetime.datetime(2019, 10, 25)

result = to_date - from_date
print(result.days)
#-------------------------------------------- Validations ---------------------
def validate_fname(value):
    if re.match(r'^[A-Za-z]{1,30}$', value):
        return True
    else:
        raise ValidationError('Enter Valid First name')

def validate_lname(value):
    if re.match(r'^([A-Za-z]{1,30}[ ]{1}|[A-Za-z]{1,30})*$', value):
        return True
    else:
        raise ValidationError('Enter Valid Last name')


def validate_name(value):
    if re.match(r'^([A-Za-z]{1,30}[ ]{1}|[A-Za-z]{1,30})*$', value):
        return True
    else:
        raise ValidationError('Enter Valid Name')

def validate_christ_email(value):
    if re.match(r'^[a-zA-Z]{3,20}[.][a-zA-Z]{1,20}[@][a-zA-Z]{2,8}.(((christuniversity)|(Christuniversity)).((in)|(com)))$', value) or re.match(r'^[a-zA-Z]{3,20}[.][a-zA-Z]{1,20}[@](((christuniversity)|(Christuniversity)).((in)|(com)))$', value) :
        return True
    else:
        raise ValidationError('Enter valid Christ email address!')

def validate_mobile(value):
    if re.match(r'^[6-9]{1}[0-9]{9}$', value):
        return True
    else:
        raise ValidationError('Enter Valid mobile number')

def validate_regno(value):
    if re.match(r'^[2-9]{1}[0-9]{6,8}$', value):
        return True
    else:
        raise ValidationError('Enter Valid Register number')

def validate_class_section(value):
    if re.match(r'^([1-9]( )[a-zA-Z]{3,4}( )[a-zA-Z]{1})$|^([1-9]( )[a-zA-Z]{3,4}( )*)$', value):
        return True
    else:
        raise ValidationError('Enter the Semester number class and section (optional) with one space in between')

def validate_class_section(value):
    if re.match(r'^([1-9]( )[a-zA-Z]{3,4}( )[a-zA-Z]{1})$|^([1-9]( )[a-zA-Z]{3,4}( )*)$', value):
        return True
    else:
        raise ValidationError('Enter the Semester number class and section (optional) with one space in between')

def validate_seven_days(value):
    print(datetime.datetime.now())

    from_date = datetime.datetime.today().date()
    to_date   = value
    print(to_date)
    result = to_date - from_date

    if result.days>7:
        return True
    else:
        raise ValidationError('Select a date 7 ahead days from today !')


#_________________________________________________________________roles table____________________________________________________________
class rolestbl(models.Model):
    roles = models.CharField(max_length=30,null=False,unique=True)

    def __str__(self):
        return (self.roles)

#_________________________________________________________________campus table____________________________________________________________
class campustbl(models.Model):
    campus= models.CharField(max_length=50,null=False,verbose_name="Campus")

    def __str__(self):
        return (self.campus)

#_________________________________________________________________department table_______________________________________________________
class depttbl(models.Model):
    dept = models.CharField(max_length=50,null=False,verbose_name="Department")

    def __str__(self):
        return (self.dept)

#_________________________________________________________________course table___________________________________________________________
class coursetbl(models.Model):
    course=models.CharField(max_length=70,null=False, verbose_name="coursename")

    def __str__(self):
        return (self.course)

#_______________________________________________________________customizing user table________________________________________________
class User(AbstractBaseUser, PermissionsMixin):

    first_name = models.CharField(('first name'), max_length=30, null=False, validators =[validate_fname])
    last_name = models.CharField(('last name'), max_length=30, null=False, validators =[validate_lname])
    mobile = models.CharField(max_length=10, verbose_name="mobile", null=False, validators =[validate_mobile])
    email = models.EmailField(('email address'), unique=True, null=False, validators =[validate_christ_email])
    usercreated_date = models.DateTimeField(('date joined'), auto_now_add=True)
    is_active = models.BooleanField(('active'), default=True)
    roles = models.ForeignKey(rolestbl,null=True, on_delete=models.SET_NULL )
    campus =models.ForeignKey(campustbl,null=True, on_delete=models.SET_NULL )
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name']

    class Meta:
        verbose_name = ('user')
        verbose_name_plural = ('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)


#_________________________________________________________________student head and volunteer profile table___________________________________________________________
#(common profile table used for both studenthead and volunteer)
class stuhead_vol_profiletbl(models.Model):

    WING_CHOICES= (
        ('One-to-One', 'One-To-One'),
        ('group', 'group'),
        )

    user = models.OneToOneField(User,on_delete=models.PROTECT)
    regno = models.CharField(max_length=10, verbose_name="Register number" ,blank = False, validators =[validate_regno] )
    course =models.ForeignKey(coursetbl,null=True, on_delete=models.SET_NULL )
    wing=models.CharField(max_length=20, choices=WING_CHOICES, verbose_name="Wing")
    sh_year=models.DateField(verbose_name="Year of being Studenthead", null=True)
    v_year=models.DateField(verbose_name="Year of being Volunteer", null=True)
    class_sec=models.CharField(max_length=20, verbose_name="Class & section" ,validators =[validate_class_section])
    passout=models.PositiveIntegerField(default=0,blank=True, verbose_name="Passout")
    total_session_hrs=models.PositiveIntegerField(default=0, verbose_name="Total_session_hrs_taken")
    no_of_sessions_conducted=models.PositiveIntegerField(default=0,verbose_name="Numberofsessionsconducted")

    def __str__(self):
        return self.user.email

# -------------------------------------------------- Session table ------------------------------------------------------
class sessiontbl(models.Model):
    session= models.CharField(max_length=30, verbose_name="session")
    description= models.CharField(max_length=200, verbose_name="description")
    session_pic=models.ImageField(null=True, blank=True,upload_to='media/sessionimages', verbose_name="Photo")
    uploaded_date=models.DateTimeField( auto_now_add=True, verbose_name="Uploaded_date")

    def __str__(self):
        return self.session

#___________________________________________________ one to one session request table____________________________________________________________
class onetoonetickettbl(models.Model):
    ONETICKET_STATUS_CHOICES= (
        ('requested', 'requested'),
        ('assigned', 'assigned'),
        ('accepted', 'accepted'),
        ('rejected', 'rejected'),
        ('work-in-progress', 'work-in-progress'),
        ('closed', 'closed'),
        )

    session = models.ForeignKey(sessiontbl,null=True, blank=True, on_delete=models.PROTECT )
    other = models.BooleanField(default=False,verbose_name="Need a new session other than the listed sessions?")
    other_desc = models.TextField(max_length=500, null=True, blank=True,verbose_name="The new session description")
    
    name = models.CharField(('Name'), max_length=30, null=False, validators =[validate_name])
    stuemail =models.EmailField(('email address'), null=False, validators =[validate_christ_email])
    mobile = models.CharField( max_length=10, null=False, validators =[validate_mobile])

    course=models.ForeignKey(coursetbl,null=True, on_delete=models.PROTECT )
    dept=models.ForeignKey(depttbl,null=True, on_delete=models.PROTECT )
    campus=models.ForeignKey(campustbl,null=True, on_delete=models.PROTECT )
    regno= models.CharField( max_length=8, null=False, validators =[validate_regno],verbose_name="Register Number")

    hours=models.PositiveIntegerField( blank=True, default = 0, verbose_name="Hours of session conducted")
    ticket_no=models.CharField(max_length=10, null=True, blank=True)
    ticket_status=models.CharField(max_length=50, choices=ONETICKET_STATUS_CHOICES, verbose_name="Status")
    request_datetime=models.DateTimeField( auto_now_add=True, verbose_name="Request datetime")
    v_feedback=models.TextField(max_length=500, null=True, blank=True, verbose_name="Volunteer Feedback")
    s_feedback=models.TextField(max_length=500, null=True, blank=True, verbose_name="Student Feedback")
    feedback_otp = models.CharField(max_length=6, null=True, blank=True, verbose_name="Feedback OTP")

    accepted_date=models.DateTimeField( auto_now_add=False, verbose_name="Accepted_date", null=True, blank= True)


templates/accounts/feedback_otp.html
{% extends 'accounts/allbase.html' %}
{% load static %}
{% load crispy_forms_tags %}

<nav>
    <div class="menu-icon">
          <i class="fa fa-bars fa-1x"></i>
    </div>
    <div class="logo">
          <img src= "{% static 'assets/img/Capslogo-own.png' %}" alt="logo" class="img-fluid">     
    </div>

    <div class="menu">
          <ul>
                <li><a href="{% url 'index_url' %}">Home</a></li>
                <li><a href="{% url 'usersessionlist_url' %}">Sessions List</a></li>
                <li><a href="{% url 'feedback_verification_url' %}">Feedback</a></li>
                <li><a href="{% url 'login_url' %}">Login</a></li>
                <li><a href="{% url 'login_url' %}"> <img src= "{% static 'assets/img/christlogo.jpg' %}" alt="logo" class="img-fluid" width="100px">  </a></li>
          </ul>
    </div>

</nav>
{% block style %}
<style>
    .form-control{
        background-color: rgb(216, 234, 249)!important;
    }

    .btn-succes{
        background-color: greenyellow;
    }
    .btn-succes:hover{
        background-color: rgb(23, 109, 13);
    }
</style>
{% endblock %}


{% block content%}


<div class="container">

    {% if messages %}
        <div class="col">
        <div class="card card-body">
        {% for message in messages %}
        <p{% if message.tags == "success" %} class="alert alert-success "{% endif %}>{{ message }}</p>
        {% if message == 'danger' %}
        <p{% if message.tags == 'danger'  %} class="alert alert-danger"{% endif %}>{{ message }}</p>
        {% endif %}
        {% endfor %}
        </div>
        </div>
    {% endif %}


    <div class="row formdiv">

        <h4 class="text-center">Enter the OTP sent to your university email</h4>
        <form action="" class="form-group" method="POST">
            {% csrf_token %}
            {{form.errors}}
            {{form}}
            <input type="submit" class="btn btn-succes m-3" value="Submit">
        </form>
    </div>
</div>


{% endblock content %}

templates/accounts/feedback_request.html
{% extends 'accounts/allbase.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block style %}
<style>
    .form-control{
        background-color: rgb(216, 234, 249)!important;
    }
    .btn{
        width: 100%;
        background-color: transparent !important;
        color: rgb(0, 0, 0);
        outline: none;
        border: 1px solid aliceblue;
    }

    .btn:hover{
        background-color: rgb(47, 151, 255) !important;
        border: 1px solid rgb(47, 151, 255);
        color: black;
    }
</style>
{% endblock %}


{% block content%}


<div class="container">

    {% if messages %}
        <div class="col">
        <div class="card card-body">
        {% for message in messages %}
        <p{% if message.tags == "success" %} class="alert alert-success "{% endif %}>{{ message }}</p>
        {% if message == 'danger' %}
        <p{% if message.tags == 'danger'  %} class="alert alert-danger"{% endif %}>{{ message }}</p>
        {% endif %}
        {% endfor %}
        </div>
        </div>
    {% endif %}


    <div class="row formdiv">
        <div class="col-md-6">
            <h4 class="text-center my-4">session Feedback/Tracking request form</h4>
            <form action="" class="form-group" method="POST">
                {% csrf_token %}
                {{form.errors}}
                {{form}}
                <input type="submit" class="btn btn-succes my-3" value="Send OTP">
            </form>
        </div>

        <div class="col-md-6">
            <img class="img-fluid" src="{% static 'accounts/assets/img/feedback.jpg' %}" alt="">
        </div>
    </div>
</div>


{% endblock content %}

templates/accounts/feedback_s_oto.html
{% extends 'accounts/allbase.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block style %}
<style>
    .form-control{
        background-color: rgb(216, 234, 249)!important;
    }

    .btn-succes{
        background-color: greenyellow;
    }
    .btn-succes:hover{
        background-color: rgb(23, 109, 13);
    }
</style>
{% endblock %}


{% block content%}


<div class="container">

    {% if messages %}
        <div class="col">
        <div class="card card-body">
        {% for message in messages %}
        <p{% if message.tags == "success" %} class="alert alert-success "{% endif %}>{{ message }}</p>
        {% if message == 'danger' %}
        <p{% if message.tags == 'danger'  %} class="alert alert-danger"{% endif %}>{{ message }}</p>
        {% endif %}
        {% endfor %}
        </div>
        </div>
    {% endif %}

    <div class="row">
        <h3>Session Details</h3>
    </div>

    <div class="row formdiv">
        <h4 class="text-center">One-to-One session Feedback form</h4>
        <form action="" class="form-group" method="POST">
            {% csrf_token %}
            {{form.errors}}
            {{form|crispy}}
            <input type="submit" class="btn btn-succes m-3" value="Submit">
        </form>
    </div>
</div>


{% endblock content %}

templates/accounts/grpbooking.html
{% extends 'accounts/allbase.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block style%}
<style>
    #id_other_desc {
        pointer-events: none;
    }

    #content{
        background: rgba(0, 0, 0, 0.7)url("{% static '/assets/img/bg-2.jpg' %}");
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-blend-mode: darken;
        color: aliceblue;
    }
    textarea{
        max-height: 90px;
    }
    .btn{
        width: 100%;
        background-color: transparent !important;
        color: aliceblue;
        outline: none;
        border: 1px solid aliceblue;
    }

    .btn:hover{
        background-color: rgb(47, 151, 255) !important;
        border: 1px solid rgb(47, 151, 255);
        color: black;
    }
</style>
{% endblock style %}

{% block content%}

  <!-- Page Content  -->
  <div id="content" class="p-4 p-md-5 pt-5 text-center">
    <div>
        <h2 class="row-4 text-center"> Peer group  Session Booking <span class="float-right"></span></h2>
    </div>
        <div class="row">
            <div class="col-md-2">


            </div>
            <div class="col-md-8 ">
           
                <form action="" method="POST">
                    {% csrf_token %}
                                        
                    {% if form.errors %}
                            <div class="alert alert-danger ">
                            {{form.errors}}
                            </div>
                        {% endif %}
                    
                    
                    <div class="form-row row m-1">
                        <div class="form-group ">
                            <label for="id_session">Session required</label>
                            {{form.session}}
                        </div>
                    </div>

                    <div class="form-row row m-1">
                        <div class="form-group ">
                            {{form.other}}
                            <label for="id_other">Please tick if you need other session which is not in the list?</label>
                        </div>
                    </div>

                    <div class="form-row row m-1">
                        <div class="form-group ">
                            <!-- <label for="id_other_desc">Description of the new session</label> -->
                            {{form.other_desc}}
                        </div>
                    </div>

                    <div class="form-row row m-1">
                        <div class="form-group  col-md-4">
                            <label for="id_name">Name</label>
                            {{form.name}}
                        </div>

                        <div class="form-group  col-md-8">
                            <label for="id_stuemail">Email id</label>
                            {{form.facultyemail}}
                        </div>
                    </div>

                    <div class="form-row row m-1">
                        <div class="form-group col-md-4 ">
                            <label for="id_mobile">Mobile</label>
                            {{form.mobile}}
                        </div>

                        <div class="form-group col-md-4 ">
                            <label for="id_campus">Campus</label>
                            {{form.campus}}
                        </div>

                        <div class="form-group col-md-2 ">
                            <label for="id_campus">Session Date</label>
                            {{form.sessiondate}}
                        </div>

                        <div class="form-group col-md-2 ">
                            <label for="id_campus">Session Time</label>
                            {{form.sessiontime}}
                        </div>
                    </div>

                    <div class="form-row row m-1">
                        <div class="form-group col-md-6 ">
                            <label for="id_course">Course</label>
                            {{form.course}}
                        </div>

                        <div class="form-group col-md-6 ">
                            <label for="id_dept">Department</label>
                            {{form.dept}}
                        </div>
                    </div>
    
                    <div class="form-row row mt-3 mx-1">
                        <div class="form-group  col-md-6">
                            <input type="submit" class="btn " value="Register">
                        </div>
                        <div class="form-group col-md-6">
                            <input type="reset" class="btn ">
                        </div>                               
                    </div>
                </form>
                
            </div>  
            
            <div class="col-md-3">
                
            </div>
        </div>
  </div>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">


    $(function () {
        $("input[id='id_other']").click(function () {
            if ($("#id_other").is(":checked")) {
                $("#id_other_desc").removeAttr("disabled");
                $('#id_other_desc').attr('required',true);
                $("#id_other_desc").focus();
                $("#id_session").val("");
                console.log("hello")
            } else {
                $("#id_other_desc").attr("disabled", "disabled");
            }
        });
    });


    // code to disable previous dates and next sven dates in datetime picker
    </script>
    
    {% endblock %}

templates/accounts/onetoonebooking.html
{% extends 'accounts/allbase.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block style%}
<style>
    #id_other_desc {
        pointer-events: none;
    }

    #content{
        background: rgba(0, 0, 0, 0.7)url("{% static '/assets/img/bg-2.jpg' %}");
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-blend-mode: darken;
        color: aliceblue;
    }
    textarea{
        max-height: 90px;
    }
    .btn{
        width: 100%;
        background-color: transparent !important;
        color: aliceblue;
        outline: none;
        border: 1px solid aliceblue;
    }

    .btn:hover{
        background-color: rgb(47, 151, 255) !important;
        border: 1px solid rgb(47, 151, 255);
        color: black;
    }
</style>
{% endblock style %}


{% block content%}
   <!-- Page Content  -->
		<div id="content" class="p-4 p-md-5 pt-5">
			<div>
				<h2 class="row-4 text-center">One-to-One Session Booking <span class="float-right"></span></h2>
			</div>
				<div class="row">
                    <div class="col-lg-2">

                    </div>

                    <div class="col-lg-8">
                    <form method="POST" class="d-flex flex-column justify-content-center">
                        {% csrf_token %}
        
                        {% if form.errors %}
                            <div class="alert alert-danger ">
                            {{form.errors}}
                            </div>
                        {% endif %}
                        
                        <div class="form-row row m-1">
                            <div class="form-group ">
                                <label for="id_session">Session required</label>
                                {{form.session}}
                            </div>
                        </div>

                        <div class="form-row row m-1">
                            <div class="form-group ">
                                {{form.other}}
                                <label for="id_other">Please tick if you need other session which is not in the list?</label>
                            </div>
                        </div>

                        <div class="form-row row m-1">
                            <div class="form-group ">
                                <!-- <label for="id_other_desc">Description of the new session</label> -->
                                {{form.other_desc}}
                            </div>
                        </div>

                        <div class="form-row row m-1">
                            <div class="form-group  col-md-4">
                                <label for="id_name">Name</label>
                                {{form.name}}
                            </div>

                            <div class="form-group  col-md-8">
                                <label for="id_stuemail">Email id</label>
                                {{form.stuemail}}
                            </div>
                        </div>

                        <div class="form-row row m-1">
                            <div class="form-group col-md-4 ">
                                <label for="id_mobile">Mobile</label>
                                {{form.mobile}}
                            </div>
    
                            <div class="form-group col-md-4 ">
                                <label for="id_regno">Register number</label>
                                {{form.regno}}
                            </div>

                            <div class="form-group col-md-4 ">
                                <label for="id_campus">Campus</label>
                                {{form.campus}}
                            </div>
                        </div>

                        <div class="form-row row m-1">
                            <div class="form-group col-md-6 ">
                                <label for="id_course">Course</label>
                                {{form.course}}
                            </div>
    
                            <div class="form-group col-md-6 ">
                                <label for="id_dept">Department</label>
                                {{form.dept}}
                            </div>
                        </div>
        
                        <div class="form-row row mt-3 mx-1">
                            <div class="form-group  col-md-6">
                                <input type="submit" class="btn " value="Register">
                            </div>
                            <div class="form-group col-md-6">
                                <input type="reset" class="btn ">
                            </div>                               
                        </div>

                    </form>   
                </div>
            </div>
		</div>
     
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
    $(function () {
        $("input[id='id_other']").click(function () {
            if ($("#id_other").is(":checked")) {
                $("#id_other_desc").removeAttr("disabled");
                $('#id_other_desc').attr('required',true);
                $("#id_other_desc").focus();
                $("#id_session").val("");
                console.log("hello")
            } else {
                $("#id_other_desc").attr("disabled", "disabled");
            }
        });
    });
    </script>
    
{% endblock %}

templates/accounts/pwd_reset_complete.html
{% extends 'accounts/pwd_base.html'%}


	{% block content %} 
	  
	  <!--Password Reset Complete-->
		<div class="container p-4">
			<h2 class="font-weight-bold mt-3">Password reset complete</h2>
			<hr>
			<p>Your password has been set. You may go ahead and log in now.</p>                 
			<a href="/login" class="btn btn-primary">Log in</a>
		</div>
	
	{% endblock %}

templates/accounts/pwd_reset_confirm.html
{% extends 'accounts/pwd_base.html'%}

{% block content %}

  {% load crispy_forms_tags %}  
  
  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}                    
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>

{% endblock %}

templates/accounts/pwd_reset_done.html
{% extends 'accounts/pwd_base.html'%}

{% block content %}

	<!--Password reset sent-->
	<div class="container p-5">
  	<h2 class="font-weight-bold mt-3">Password reset sent</h2>
		<hr>
		<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
  </div>

{% endblock %}