CAPS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('superadmin/', include('superadmin.urls')),
    path('mentor/', include('mentor.urls')),
    path('volunteer/', include('volunteer.urls')),

    # path('accounts/', include('django.contrib.auth.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.core.exceptions import ValidationError

from .managers import UserManager

import re
import datetime

from_date = datetime.datetime(2019, 10, 21)

to_date   = datetime.datetime(2019, 10, 25)

result = to_date - from_date
print(result.days)
#-------------------------------------------- Validations ---------------------
def validate_fname(value):
    if re.match(r'^[A-Za-z]{1,30}$', value):
        return True
    else:
        raise ValidationError('Enter Valid First name')

def validate_lname(value):
    if re.match(r'^([A-Za-z]{1,30}[ ]{1}|[A-Za-z]{1,30})*$', value):
        return True
    else:
        raise ValidationError('Enter Valid Last name')


def validate_name(value):
    if re.match(r'^([A-Za-z]{1,30}[ ]{1}|[A-Za-z]{1,30})*$', value):
        return True
    else:
        raise ValidationError('Enter Valid Name')

def validate_christ_email(value):
    if re.match(r'^[a-zA-Z]{3,20}[.][a-zA-Z]{1,20}[@][a-zA-Z]{2,8}.(((christuniversity)|(Christuniversity)).((in)|(com)))$', value) or re.match(r'^[a-zA-Z]{3,20}[.][a-zA-Z]{1,20}[@](((christuniversity)|(Christuniversity)).((in)|(com)))$', value) :
        return True
    else:
        raise ValidationError('Enter valid Christ email address!')

def validate_mobile(value):
    if re.match(r'^[6-9]{1}[0-9]{9}$', value):
        return True
    else:
        raise ValidationError('Enter Valid mobile number')

def validate_regno(value):
    if re.match(r'^[2-9]{1}[0-9]{6,8}$', value):
        return True
    else:
        raise ValidationError('Enter Valid Register number')

def validate_class_section(value):
    if re.match(r'^([1-9]( )[a-zA-Z]{3,4}( )[a-zA-Z]{1})$|^([1-9]( )[a-zA-Z]{3,4}( )*)$', value):
        return True
    else:
        raise ValidationError('Enter the Semester number class and section (optional) with one space in between')

def validate_class_section(value):
    if re.match(r'^([1-9]( )[a-zA-Z]{3,4}( )[a-zA-Z]{1})$|^([1-9]( )[a-zA-Z]{3,4}( )*)$', value):
        return True
    else:
        raise ValidationError('Enter the Semester number class and section (optional) with one space in between')

def validate_seven_days(value):
    print(datetime.datetime.now())

    from_date = datetime.datetime.today().date()
    to_date   = value
    print(to_date)
    result = to_date - from_date

    if result.days>7:
        return True
    else:
        raise ValidationError('Select a date 7 ahead days from today !')


#_________________________________________________________________roles table____________________________________________________________
class rolestbl(models.Model):
    roles = models.CharField(max_length=30,null=False,unique=True)

    def __str__(self):
        return (self.roles)

#_________________________________________________________________campus table____________________________________________________________
class campustbl(models.Model):
    campus= models.CharField(max_length=50,null=False,verbose_name="Campus")

    def __str__(self):
        return (self.campus)

#_________________________________________________________________department table_______________________________________________________
class depttbl(models.Model):
    dept = models.CharField(max_length=50,null=False,verbose_name="Department")

    def __str__(self):
        return (self.dept)

#_________________________________________________________________course table___________________________________________________________
class coursetbl(models.Model):
    course=models.CharField(max_length=70,null=False, verbose_name="coursename")

    def __str__(self):
        return (self.course)

#_______________________________________________________________customizing user table________________________________________________
class User(AbstractBaseUser, PermissionsMixin):

    first_name = models.CharField(('first name'), max_length=30, null=False, validators =[validate_fname])
    last_name = models.CharField(('last name'), max_length=30, null=False, validators =[validate_lname])
    mobile = models.CharField(max_length=10, verbose_name="mobile", null=False, validators =[validate_mobile])
    email = models.EmailField(('email address'), unique=True, null=False, validators =[validate_christ_email])
    usercreated_date = models.DateTimeField(('date joined'), auto_now_add=True)
    is_active = models.BooleanField(('active'), default=True)
    roles = models.ForeignKey(rolestbl,null=True, on_delete=models.SET_NULL )
    campus =models.ForeignKey(campustbl,null=True, on_delete=models.SET_NULL )
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name']

    class Meta:
        verbose_name = ('user')
        verbose_name_plural = ('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)


#_________________________________________________________________student head and volunteer profile table___________________________________________________________
#(common profile table used for both studenthead and volunteer)
class stuhead_vol_profiletbl(models.Model):

    WING_CHOICES= (
        ('One-to-One', 'One-To-One'),
        ('group', 'group'),
        )

    user = models.OneToOneField(User,on_delete=models.PROTECT)
    regno = models.CharField(max_length=10, verbose_name="Register number" ,blank = False, validators =[validate_regno] )
    course =models.ForeignKey(coursetbl,null=True, on_delete=models.SET_NULL )
    wing=models.CharField(max_length=20, choices=WING_CHOICES, verbose_name="Wing")
    sh_year=models.DateField(verbose_name="Year of being Studenthead", null=True)
    v_year=models.DateField(verbose_name="Year of being Volunteer", null=True)
    class_sec=models.CharField(max_length=20, verbose_name="Class & section" ,validators =[validate_class_section])
    passout=models.PositiveIntegerField(default=0,blank=True, verbose_name="Passout")
    total_session_hrs=models.PositiveIntegerField(default=0, verbose_name="Total_session_hrs_taken")
    no_of_sessions_conducted=models.PositiveIntegerField(default=0,verbose_name="Numberofsessionsconducted")

    def __str__(self):
        return self.user.email

# -------------------------------------------------- Session table ------------------------------------------------------
class sessiontbl(models.Model):
    session= models.CharField(max_length=30, verbose_name="session")
    description= models.CharField(max_length=200, verbose_name="description")
    session_pic=models.ImageField(null=True, blank=True,upload_to='media/sessionimages', verbose_name="Photo")
    uploaded_date=models.DateTimeField( auto_now_add=True, verbose_name="Uploaded_date")

    def __str__(self):
        return self.session

#___________________________________________________ one to one session request table____________________________________________________________
class onetoonetickettbl(models.Model):
    ONETICKET_STATUS_CHOICES= (
        ('requested', 'requested'),
        ('assigned', 'assigned'),
        ('accepted', 'accepted'),
        ('rejected', 'rejected'),
        ('work-in-progress', 'work-in-progress'),
        ('closed', 'closed'),
        )

    session = models.ForeignKey(sessiontbl,null=True, blank=True, on_delete=models.PROTECT )
    other = models.BooleanField(default=False,verbose_name="Need a new session other than the listed sessions?")
    other_desc = models.TextField(max_length=500, null=True, blank=True,verbose_name="The new session description")
    
    name = models.CharField(('Name'), max_length=30, null=False, validators =[validate_name])
    stuemail =models.EmailField(('email address'), null=False, validators =[validate_christ_email])
    mobile = models.CharField( max_length=10, null=False, validators =[validate_mobile])

    course=models.ForeignKey(coursetbl,null=True, on_delete=models.PROTECT )
    dept=models.ForeignKey(depttbl,null=True, on_delete=models.PROTECT )
    campus=models.ForeignKey(campustbl,null=True, on_delete=models.PROTECT )
    regno= models.CharField( max_length=8, null=False, validators =[validate_regno],verbose_name="Register Number")

    hours=models.PositiveIntegerField( blank=True, default = 0, verbose_name="Hours of session conducted")
    ticket_no=models.CharField(max_length=10, null=True, blank=True)
    ticket_status=models.CharField(max_length=50, choices=ONETICKET_STATUS_CHOICES, verbose_name="Status")
    request_datetime=models.DateTimeField( auto_now_add=True, verbose_name="Request datetime")
    v_feedback=models.TextField(max_length=500, null=True, blank=True, verbose_name="Volunteer Feedback")
    s_feedback=models.TextField(max_length=500, null=True, blank=True, verbose_name="Student Feedback")
    feedback_otp = models.CharField(max_length=6, null=True, blank=True, verbose_name="Feedback OTP")

    accepted_date=models.DateTimeField( auto_now_add=False, verbose_name="Accepted_date", null=True, blank= True)


templates/studenthead/sh_base.html
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <title>CAPS dashboard</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--Bootsrap 5 CDN for CSS framework-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">

    {% block style%}

    {% endblock style %}
  

  </head>

  <body>
        
    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
            <div class="custom-menu">
                <button type="button" id="sidebarCollapse" class="btn btn-primary">
                    <i class="fa fa-bars"></i>
                    <span class="sr-only">Toggle Menu</span>
                </button>
            </div>
            <div class="p-4 pt-5">
                <h1><img class="img-fluid" src="{% static 'assets/img/Capslogo-own.png' %}" alt=""><a href="index.html" class="logo"></a></h1>
                <ul class="list-unstyled components mb-5">

                   

                    {% if request.user.stuhead_vol_profiletbl.wing == 'One-to-One'%}
                    <li class="active">
                        <a href="{% url 'sh_dashboard_url' %}">Dashboard</a>
                    </li>

                    <li class="active">
                        <a href="{% url 'sh_oto_list_url' %}">One-to-One sessions</a>
                    </li>

                    <li class="active">
                        <a href="{% url 'sh_my_oto_list_url' %}">My One-to-One sessions</a>
                    </li>

                    {% elif request.user.stuhead_vol_profiletbl.wing == 'group'%}
                    <li class="active">
                        <a href="{% url 'sh_dashboard_url' %}">Dashboard</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'sh_group_list_url' %}">Group sessions</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'sh_my_group_list_url' %}">My Group sessions</a>
                    </li>

                    {% endif %}
                    
                    <li>
                        <a href="#pageSubmenu3" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Volunteers</a>
                        <ul class="collapse list-unstyled" id="pageSubmenu3">
                        <li>
                            <a href="{% url 'sh_volunteer_add_url' %}">Add New Volunteers</a>
                        </li>
                        <li>
                            <a href="{% url 'sh_volunteer_list_url' %}">All Volunteers list</a>
                        </li>
                        </ul>
                    </li>

           
                    <li>
                        <a href="#">Help</a>
                    </li>
                </ul>

                <div class="mb-5">
                    <div class="form-group">
                        <a href="{% url 'logout_url' %}" class="btn btn-block p-2 logoutbtn">LOGOUT</a>
                    </div>
                </div>

                <div class="footer">
                    <p>CAPS @ christuniversity.in</p>
                </div>

            </div>
        </nav>

        

        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-2 pt-2 ">
            <!-- Header -->
            <div class="container header-bar p-3">
                <div class="d-md-flex  flex-sm-row align-items-center justify-content-between">
                    <div class=""><img src="{% static 'images/capslogo1.png' %}" class="navbar-brand img-fluid pl-3" alt="" width="100px"></div>
                    <div class=""><h4 style="margin:0;">StudentHead Dashboard</h4></div>
                    <div class=""><h5><small>{{request.user.email}}</small></h5></div>
                </div>
            </div>

          
            
            <!-- Messages -->
            {% for message in messages %}
            <div class="container-fluid p-3">
            <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
                </button>
                {{ message }}
            </div>
            </div>
            {% endfor %}

            {% block content %}
            {% endblock %}
            
        </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    {% block script %}
    {% endblock %}
  </body>
</html>

templates/studenthead/sh_group_assign_form.html
{% extends 'studenthead/sh_base.html' %}
{% load static %}

{% block style%}
<style>
    .mybtn {
        background-color: rgb(129, 255, 127);
        border: none;
        width:40%;
        border-radius: 1rem;
        height: 2.6rem;
        transition: .3s;
    }

    .mybtn:hover {
        background-color: rgb(40, 105, 39);
        color: aliceblue;
    }
</style>
{% endblock style %}

{% block content%}
 <!-- form  -->
 <div class="container p-3">
    <div class="row d-flex formdiv">
        <div class="col">
            <h4 class="pb-3">Group session assign form {{accept}}</h4>

           
            {% if form.errors %}
            <div class="alert alert-danger alert-dismissable">
              <p>{{form.errors}}</p>
             
            </div>
            {% endif %}
            
            <form action="" method="POST">
                {% csrf_token %}
            
                
            
                {% if userlist %}
                <label for="id_vol1">volunteer1</label>
                <select name="vol1" id="id_vol1" class="form-control" initial>
                    <option value="" selected disabled hidden>Choose here</option>
                    {% for each in userlist %}
                    <option value="{{ each.id }}">{{ each.email }}</option>
                    {% endfor %}
                </select>
                {% endif %}
            
                {% if userlist %}
                <label for="id_vol2">volunteer2</label>
                <select name="vol2" id="id_vol2" class="form-control" initial>
                    <option value="" selected disabled hidden>Choose here</option>
                    {% for each in userlist %}
                    <option value="{{ each.id }}">{{ each.email }}</option>
                    {% endfor %}
                </select>
                {% endif %}
            
                {% if userlist %}
                <label for="id_vol3">volunteer3</label>
                <select name="vol3" id="id_vol3" class="form-control" initial>
                    <option value="" selected disabled hidden>Choose here</option>
                    {% for each in userlist %}
                    <option value="{{ each.id }}">{{ each.email }}</option>
                    {% endfor %}
                </select>
                {% endif %}
            
                {% if userlist %}
                <label for="id_vol4">volunteer4</label>
                <select name="vol4" id="id_vol4" class="form-control" initial>
                    <option value="" selected disabled hidden>Choose here</option>
                    {% for each in userlist %}
                    <option value="{{ each.id }}">{{ each.email }}</option>
                    {% endfor %}
                </select>
                {% endif %}
            
                <button class="my-3 mybtn" type="submit">Assign </button>
               
            </form>
        </div>
    </div>
</div>



</div>
{% endblock content %}

{% block script%}
{% endblock script %}




templates/studenthead/sh_my_group_feedback.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form action="" method="post">

        <h2>group feedback</h2><hr>
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>

</body>
</html>

templates/studenthead/sh_my_oto_feedback.html
{% extends 'studenthead/sh_base.html' %}
{% load static %}

{% block style%}
<style>
    #id_v_feedback{
        height:200px !important;
        background-color: aliceblue;
    }
</style>
{% endblock style %}

{% block content%}
<div class="container p-3">
    <div class="row d-flex formdiv">
        <div class="col">
            <h4 class="pb-3">STudent head Feedback for one-toone session</h4>

           
            <!-- Messages -->
            {% if messages %}
            {% for message in messages %}
            
            <div class="alert alert-danger alert-dismissible fade show my-3" role="alert">
                {{message}}
                {{form.errors}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
 
            {% endfor %}
            {% endif %}
           
            
            <form method="POST">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_email">Your feedback</label>
                    {{form.v_feedback}}
                </div>

                <div class="form-group">
                  <label for="id_mobile">Number of hours </label>
                  {{form.hours}}
                </div>
                
                
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <input type="submit" class="btn btn-primary btn-block" value="Submit feedback and close">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="reset" class="btn btn-block btn-light">
                    </div>                               
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

templates/studenthead/sh_oto_assign_form.html
{% extends 'studenthead/sh_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content%}

<!-- Messages -->
{% if messages %}
{% for message in messages %}

<div class="alert alert-danger alert-dismissible fade show my-3" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
</div>

{% endfor %}
{% endif %}
		
<!-- Oto request List -->
<div class="container list p-3">
    <div class="row formdiv">
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit">
            <input type="reset">
        </form>
    </div>
</div>
            
{% endblock %}



templates/studenthead/sh_volunteer_add.html
{% extends 'studenthead/sh_base.html' %}
{% load static %}

{% block style%}
{% endblock style%}

{% block content%}
<!-- form  -->
<div class="container p-3">
    <div class="row d-flex formdiv">
        <div class="col">
            <h4 class="pb-3">New Volunteer Registration</h4>

           
            <!-- Messages -->
            {% if messages %}
            {% for message in messages %}
            
            <div class="alert alert-danger alert-dismissible fade show my-3" role="alert">
                {{message}}
                {{form1.errors}}
                {{form2.errors}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
 
            {% endfor %}
            {% endif %}
           
            
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_email">Email Address (given by ChristUniversity)*</label>
                    {{form1.email}}
                </div>

                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label for="id_firstname">First name*</label>
                    {{form1.first_name}}
                    <!-- <input type="email" class="form-control" id="inputEmail4" placeholder="Email"> -->
                  </div>
                  <div class="form-group col-md-6">
                    <label for="id_lastname">Last name</label>
                    {{form1.last_name}}
                    <!-- <input type="email" class="form-control" id="inputEmail4" placeholder="Email"> -->
                  </div>
                </div>

                <div class="form-group">
                  <label for="id_mobile">Mobile number</label>
                  {{form1.mobile}}
                </div>
                
                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label for="id_password1">Password (min 8 characters)</label>
                    {{form1.password1}}
                  </div>
                  <div class="form-group col-md-6">
                    <label for="id_password1">Password Again</label>
                    {{form1.password2}}
                  </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="id_password1">Campus</label>
                        {{form1.campus}}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="id_password1">Course</label>
                        {{form2.course}}
                    </div>
                    <div class="form-group col-md-4">
                      <label for="id_password1">CAPS wing</label>
                      {{form2.wing}}
                  </div>
                    <div class="form-group col-md-3">
                        <label for="id_password1">Class & section</label>
                        {{form2.class_sec}}
                    </div>
                    <div class="form-group col-md-3">
                      <label for="id_password1">Register Number</label>
                      {{form2.regno}}
                  </div>
                  <div class="form-group col-md-4">
                    <label for="id_passout">Passout</label>
                    {{form2.passout}}
                </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <input type="submit" class="btn btn-primary btn-block" value="Register">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="reset" class="btn btn-block btn-light">
                    </div>                               
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

templates/studenthead/sh_volunteer_update.html
{% extends 'studenthead/sh_base.html' %}
{% load static %}

{% block style%}
{% endblock style%}

{% block content%}
<!-- form  -->
<div class="container p-3">
    <div class="row d-flex formdiv">
        <div class="col">
            <h4 class="pb-3">Update Volunteer</h4>

           
            <!-- Messages -->
            {% if messages %}
            {% for message in messages %}
            
            <div class="alert alert-danger alert-dismissible fade show my-3" role="alert">
                {{message}}
                {{form1.errors}}
                {{form2.errors}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
 
            {% endfor %}
            {% endif %}
           
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_email">Email Address (given by ChristUniversity)*</label>
                    {{form1.email}}
                </div>

                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label for="id_firstname">First name*</label>
                    {{form1.first_name}}
                    <!-- <input type="email" class="form-control" id="inputEmail4" placeholder="Email"> -->
                  </div>
                  <div class="form-group col-md-6">
                    <label for="id_lastname">Last name</label>
                    {{form1.last_name}}
                    <!-- <input type="email" class="form-control" id="inputEmail4" placeholder="Email"> -->
                  </div>
                </div>

                <div class="form-group">
                  <label for="id_mobile">Mobile number</label>
                  {{form1.mobile}}
                </div>
                
                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label for="id_password1">Password (min 8 characters)</label>
                    {{form1.password1}}
                  </div>
                  <div class="form-group col-md-6">
                    <label for="id_password1">Password Again</label>
                    {{form1.password2}}
                  </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="id_password1">Campus</label>
                        {{form2.campus}}
                    </div>
                    <div class="form-group col-md-4">
                        <label for="id_password1">Course</label>
                        {{form2.course}}
                    </div>
                    <div class="form-group col-md-4">
                      <label for="id_password1">CAPS wing</label>
                      {{form2.wing}}
                  </div>
                    <div class="form-group col-md-3">
                        <label for="id_password1">Class & section</label>
                        {{form2.class_sec}}
                    </div>
                    <div class="form-group col-md-3">
                      <label for="id_password1">Register Number</label>
                      {{form2.regno}}
                  </div>
                    <div class="form-group col-md-3">
                        <label for="id_password1">Passout</label>
                        {{form2.passout}}
                    </div>
                    
                </div>
            

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <input type="submit" class="btn btn-primary btn-block" value="Register">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="reset" class="btn btn-block btn-light">
                    </div>                               
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}