CAPS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('superadmin/', include('superadmin.urls')),
    path('mentor/', include('mentor.urls')),
    path('volunteer/', include('volunteer.urls')),

    # path('accounts/', include('django.contrib.auth.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

superadmin/urls.py
from django.urls import path,include
from .import views

urlpatterns = [

    #**************************************************dept url************************************************************
    path('deptaddform/',views.deptaddformfunc, name='sa_dept_add_url'),
    path('deptlist/',views.deptlistfunc, name='sa_dept_list_url'),
    path('deptupdate/<int:pkid>',views.deptupdatefunc, name='sa_dept_update_url'),
    path('deptdelete/<int:pkid>',views.deptdeletefunc, name='sa_dept_delete_url'),

    
    #**************************************************course url************************************************************
    path('courseaddform/',views.courseaddformfunc, name='sa_course_add_url'),
    path('courselist/',views.courselistfunc, name='sa_course_list_url'),
    path('courseupdate/<int:pkid>',views.courseupdatefunc, name='sa_course_update_url'),
    path('coursedelete/<int:pkid>',views.coursedeletefunc, name='sa_course_delete_url'),

    #**************************************************campus url************************************************************
    path('campusaddform/',views.campusaddformfunc, name='sa_campus_add_url'),
    path('campuslist/',views.campuslistfunc, name='sa_campus_list_url'),
    path('campusupdate/<int:pkid>',views.campusupdatefunc, name='sa_campus_update_url'),
    path('campusdelete/<int:pkid>',views.campusdeletefunc, name='sa_campus_delete_url'),

    #**************************************************Session url************************************************************
    path('sessionaddform/',views.sa_session_add_func, name='sa_session_add_url'),
    path('sessionlist/',views.sa_session_list_func, name='sa_session_list_url'),
    path('sessionupdate/<int:pkid>',views.sa_session_update_func, name='sa_session_update_url'),
    path('sessiondelete/<int:pkid>',views.sa_session_delete_func, name='sa_session_delete_url'),

    #**************************************************super admin url************************************************************
    path('superadmindashboard/',views.sa_dashboard_func, name='sa_dashboard_url'),

    # ---------------------------------------------- Mentors -------------------------------->
    path('mentorlist/',views.sa_mentor_list_func, name='sa_mentor_list_url'),
    path('mentoradd/',views.sa_mentor_add_func, name='sa_mentor_add_url'),
    path('mentorupdate/<int:pkid>',views.sa_mentor_update_func, name='sa_mentor_update_url'),
    path('mentorinactive/<int:pkid>',views.set_user_inactive_mentor_func, name='set_user_inactive_mentor_url'),
    path('mentoractive/<int:pkid>',views.set_user_active_mentor_func, name='set_user_active_mentor_url'),


    # --------------------------------------------- One to one sessions -------------------->
    path('otolist/',views.sa_oto_list_func, name='sa_oto_list_url'),

    path('grouplist/',views.sa_group_list_func, name='sa_group_list_url'),

    path('otodetails/<int:pkid>',views.sa_oto_detail_func, name='sa_oto_detail_url'),

    path('groupdetails/<int:pkid>',views.sa_grp_detail_func, name='sa_grp_detail_url'),

]



accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.core.exceptions import ValidationError

from .managers import UserManager

import re
import datetime

from_date = datetime.datetime(2019, 10, 21)

to_date   = datetime.datetime(2019, 10, 25)

result = to_date - from_date
print(result.days)
#-------------------------------------------- Validations ---------------------
def validate_fname(value):
    if re.match(r'^[A-Za-z]{1,30}$', value):
        return True
    else:
        raise ValidationError('Enter Valid First name')

def validate_lname(value):
    if re.match(r'^([A-Za-z]{1,30}[ ]{1}|[A-Za-z]{1,30})*$', value):
        return True
    else:
        raise ValidationError('Enter Valid Last name')


def validate_name(value):
    if re.match(r'^([A-Za-z]{1,30}[ ]{1}|[A-Za-z]{1,30})*$', value):
        return True
    else:
        raise ValidationError('Enter Valid Name')

def validate_christ_email(value):
    if re.match(r'^[a-zA-Z]{3,20}[.][a-zA-Z]{1,20}[@][a-zA-Z]{2,8}.(((christuniversity)|(Christuniversity)).((in)|(com)))$', value) or re.match(r'^[a-zA-Z]{3,20}[.][a-zA-Z]{1,20}[@](((christuniversity)|(Christuniversity)).((in)|(com)))$', value) :
        return True
    else:
        raise ValidationError('Enter valid Christ email address!')

def validate_mobile(value):
    if re.match(r'^[6-9]{1}[0-9]{9}$', value):
        return True
    else:
        raise ValidationError('Enter Valid mobile number')

def validate_regno(value):
    if re.match(r'^[2-9]{1}[0-9]{6,8}$', value):
        return True
    else:
        raise ValidationError('Enter Valid Register number')

def validate_class_section(value):
    if re.match(r'^([1-9]( )[a-zA-Z]{3,4}( )[a-zA-Z]{1})$|^([1-9]( )[a-zA-Z]{3,4}( )*)$', value):
        return True
    else:
        raise ValidationError('Enter the Semester number class and section (optional) with one space in between')

def validate_class_section(value):
    if re.match(r'^([1-9]( )[a-zA-Z]{3,4}( )[a-zA-Z]{1})$|^([1-9]( )[a-zA-Z]{3,4}( )*)$', value):
        return True
    else:
        raise ValidationError('Enter the Semester number class and section (optional) with one space in between')

def validate_seven_days(value):
    print(datetime.datetime.now())

    from_date = datetime.datetime.today().date()
    to_date   = value
    print(to_date)
    result = to_date - from_date

    if result.days>7:
        return True
    else:
        raise ValidationError('Select a date 7 ahead days from today !')


#_________________________________________________________________roles table____________________________________________________________
class rolestbl(models.Model):
    roles = models.CharField(max_length=30,null=False,unique=True)

    def __str__(self):
        return (self.roles)

#_________________________________________________________________campus table____________________________________________________________
class campustbl(models.Model):
    campus= models.CharField(max_length=50,null=False,verbose_name="Campus")

    def __str__(self):
        return (self.campus)

#_________________________________________________________________department table_______________________________________________________
class depttbl(models.Model):
    dept = models.CharField(max_length=50,null=False,verbose_name="Department")

    def __str__(self):
        return (self.dept)

#_________________________________________________________________course table___________________________________________________________
class coursetbl(models.Model):
    course=models.CharField(max_length=70,null=False, verbose_name="coursename")

    def __str__(self):
        return (self.course)

#_______________________________________________________________customizing user table________________________________________________
class User(AbstractBaseUser, PermissionsMixin):

    first_name = models.CharField(('first name'), max_length=30, null=False, validators =[validate_fname])
    last_name = models.CharField(('last name'), max_length=30, null=False, validators =[validate_lname])
    mobile = models.CharField(max_length=10, verbose_name="mobile", null=False, validators =[validate_mobile])
    email = models.EmailField(('email address'), unique=True, null=False, validators =[validate_christ_email])
    usercreated_date = models.DateTimeField(('date joined'), auto_now_add=True)
    is_active = models.BooleanField(('active'), default=True)
    roles = models.ForeignKey(rolestbl,null=True, on_delete=models.SET_NULL )
    campus =models.ForeignKey(campustbl,null=True, on_delete=models.SET_NULL )
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name']

    class Meta:
        verbose_name = ('user')
        verbose_name_plural = ('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)


#_________________________________________________________________student head and volunteer profile table___________________________________________________________
#(common profile table used for both studenthead and volunteer)
class stuhead_vol_profiletbl(models.Model):

    WING_CHOICES= (
        ('One-to-One', 'One-To-One'),
        ('group', 'group'),
        )

    user = models.OneToOneField(User,on_delete=models.PROTECT)
    regno = models.CharField(max_length=10, verbose_name="Register number" ,blank = False, validators =[validate_regno] )
    course =models.ForeignKey(coursetbl,null=True, on_delete=models.SET_NULL )
    wing=models.CharField(max_length=20, choices=WING_CHOICES, verbose_name="Wing")
    sh_year=models.DateField(verbose_name="Year of being Studenthead", null=True)
    v_year=models.DateField(verbose_name="Year of being Volunteer", null=True)
    class_sec=models.CharField(max_length=20, verbose_name="Class & section" ,validators =[validate_class_section])
    passout=models.PositiveIntegerField(default=0,blank=True, verbose_name="Passout")
    total_session_hrs=models.PositiveIntegerField(default=0, verbose_name="Total_session_hrs_taken")
    no_of_sessions_conducted=models.PositiveIntegerField(default=0,verbose_name="Numberofsessionsconducted")

    def __str__(self):
        return self.user.email

# -------------------------------------------------- Session table ------------------------------------------------------
class sessiontbl(models.Model):
    session= models.CharField(max_length=30, verbose_name="session")
    description= models.CharField(max_length=200, verbose_name="description")
    session_pic=models.ImageField(null=True, blank=True,upload_to='media/sessionimages', verbose_name="Photo")
    uploaded_date=models.DateTimeField( auto_now_add=True, verbose_name="Uploaded_date")

    def __str__(self):
        return self.session

#___________________________________________________ one to one session request table____________________________________________________________
class onetoonetickettbl(models.Model):
    ONETICKET_STATUS_CHOICES= (
        ('requested', 'requested'),
        ('assigned', 'assigned'),
        ('accepted', 'accepted'),
        ('rejected', 'rejected'),
        ('work-in-progress', 'work-in-progress'),
        ('closed', 'closed'),
        )

    session = models.ForeignKey(sessiontbl,null=True, blank=True, on_delete=models.PROTECT )
    other = models.BooleanField(default=False,verbose_name="Need a new session other than the listed sessions?")
    other_desc = models.TextField(max_length=500, null=True, blank=True,verbose_name="The new session description")
    
    name = models.CharField(('Name'), max_length=30, null=False, validators =[validate_name])
    stuemail =models.EmailField(('email address'), null=False, validators =[validate_christ_email])
    mobile = models.CharField( max_length=10, null=False, validators =[validate_mobile])

    course=models.ForeignKey(coursetbl,null=True, on_delete=models.PROTECT )
    dept=models.ForeignKey(depttbl,null=True, on_delete=models.PROTECT )
    campus=models.ForeignKey(campustbl,null=True, on_delete=models.PROTECT )
    regno= models.CharField( max_length=8, null=False, validators =[validate_regno],verbose_name="Register Number")

    hours=models.PositiveIntegerField( blank=True, default = 0, verbose_name="Hours of session conducted")
    ticket_no=models.CharField(max_length=10, null=True, blank=True)
    ticket_status=models.CharField(max_length=50, choices=ONETICKET_STATUS_CHOICES, verbose_name="Status")
    request_datetime=models.DateTimeField( auto_now_add=True, verbose_name="Request datetime")
    v_feedback=models.TextField(max_length=500, null=True, blank=True, verbose_name="Volunteer Feedback")
    s_feedback=models.TextField(max_length=500, null=True, blank=True, verbose_name="Student Feedback")
    feedback_otp = models.CharField(max_length=6, null=True, blank=True, verbose_name="Feedback OTP")

    accepted_date=models.DateTimeField( auto_now_add=False, verbose_name="Accepted_date", null=True, blank= True)


superadmin/models.py
from django.db import models

# Create your models here.

templates/superadmin/sa_campus_list.html
{% extends 'superadmin/sa_base.html' %}
{% load static %}

{% block content%}

<!-- Messages -->
{% if messages %}
{% for message in messages %}

<div class="alert alert-danger alert-dismissible fade show my-3" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
</div>

{% endfor %}
{% endif %}
<!-- campus List -->
<div class="container list p-3">
    <div class="row formdiv">
        <h4 class="form-header">Campus List</h4>

        <div class="table-responsive">
        <table class="table  table-hover">
            <tr class=" text-white text-center rounded-1 tablelist" id="tablelist">
                <th>Slno</th>
                <th>Campus</th>
            </tr>
            

            {% for each in templist %}
            <tr class="text-center">
                <td>{{forloop.counter}}</td>
                <td>{{each.campus}}</td>
            </tr>
            {% endfor %}
            
        </table>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

templates/superadmin/sa_campus_update.html
{% extends 'superadmin/sa_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
	
	<div class="row formdiv">
		<h4>update campus details</h4>
		<div class="col">
			<form action="" method="POST">
				{% csrf_token %}
				{{form|crispy}}
				<div class="row p-3">
					<div class="col-4"></div>
					<div class="col-4">
					<button class="btn btn-primary" name="create" id="create" type="submit" onclick="return confirm('Are you sure to update the Campus name?')">Submit</button>	
					</div>
					<div class="col-4"></div>
				</div>
			</form>
			
		</div>			
	</div>

<div class="col-4"></div>
</div>
{% endblock %}

templates/superadmin/sa_course_add.html
{% extends 'superadmin/sa_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content%}
		
<!-- Page Content  -->
<div id="content" class="p-4 p-md-5 text-center">
		
	<div class="container">
		<div class="row formdiv">
			<h4>Add new Course</h4>

			<form action=""  method="POST">
				{% csrf_token %}
				{% if form.errors %}
					<div class="alert alert-danger">
						{{form.errors}}
					</div>
				{% endif %}

				{{form|crispy}}
				<input type="submit" class=" btn btn-primary" onclick="return confirm('Are you sure to Add new course?')">
			</form>
		</div>
	</div>

	<!-- campus List -->
	<div class="container list p-3">
		<div class="row formdiv">
			<h4 class="form-header">Course List</h4>

			<div class="table-responsive">
			<table class="table  table-hover">
				<tr class=" text-white text-center rounded-1 tablelist" id="tablelist">
					<th>Slno</th>
					<th>Course name</th>
					<th>Action</th>
				</tr>

				{% for each in templist %}
				<tr class="text-center">
					<td>{{forloop.counter}}</td>
					<td>{{each.course}}</td>
					<td>
						<a class="btn btn-danger m-1" href="{% url 'sa_course_delete_url' each.id %}" onclick="return confirm('Are you sure to delete the course?')">Delete</a>
						<a class="btn btn-primary m-1" href="{% url 'sa_course_update_url' each.id %}">Update</a>
					</td>
				</tr>
				{% endfor %}
				
			</table>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/superadmin/sa_course_list.html
{% extends 'superadmin/sa_base.html' %}
{% load static %}

{% block content%}

<!-- Messages -->
{% if messages %}
{% for message in messages %}

<div class="alert alert-danger alert-dismissible fade show my-3" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
</div>

{% endfor %}
{% endif %}
<!-- Volunteer List -->
<div class="container list p-3">
    <div class="row formdiv">
        <h4 class="form-header">Course List</h4>

        <div class="table-responsive">
        <table class="table  table-hover">
            <tr class=" text-white text-center rounded-1 tablelist" id="tablelist">
                <th>Slno</th>
                <th>Course</th>
                <th>Action</th>
            </tr>
            

            {% for each in templist %}
            <tr class="text-center">
                <td>{{forloop.counter}}</td>
                <td>{{each.course}}</td>
                <td>
                    <Button class="btn btn-danger">Edit</Button>
                    <button class="btn btn-danger">Delete</button>
                </td>
            </tr>
            {% endfor %}
            
        </table>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

templates/superadmin/sa_course_update.html
{% extends 'superadmin/sa_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
	
	<div class="row formdiv">
		<h4>update Course details</h4>
		<div class="col">
			<form action="" method="POST">
				{% csrf_token %}
				{{form|crispy}}
				<div class="row p-3">
					<div class="col-4"></div>
					<div class="col-4">
					<button class="btn btn-primary" name="create" id="create" type="submit" onclick="return confirm('Are you sure to update the course?')">Submit</button>	
					</div>
					<div class="col-4"></div>
				</div>
			</form>
			
		</div>	
	</div>
</div>
{% endblock %}

templates/superadmin/sa_dept_add.html
{% extends 'superadmin/sa_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content%}
		
<!-- Page Content  -->
<div id="content" class="p-4 p-md-5 text-center">
		
	<div class="container">
		<div class="row formdiv">
			<h4>Add new Department</h4>

			<form action=""  method="POST">
				{% csrf_token %}
				{% if form.errors %}
					<div class="alert alert-danger">
						{{form.errors}}
					</div>
				{% endif %}

				{{form|crispy}}
				<input type="submit" class=" btn btn-primary" onclick="return confirm('Are you sure to add the new Department?')">
			</form>
		</div>
	</div>

	<!-- campus List -->
	<div class="container list p-3">
		<div class="row formdiv">
			<h4 class="form-header">Department List</h4>

			<div class="table-responsive">
			<table class="table  table-hover">
				<tr class=" text-white text-center rounded-1 tablelist" id="tablelist">
					<th>Slno</th>
					<th>Department</th>
					<th>Action</th>
				</tr>

				{% for each in templist %}
				<tr class="text-center">
					<td>{{forloop.counter}}</td>
					<td>{{each.dept}}</td>
					<td>
						<a class="btn btn-danger m-1" href="{% url 'sa_dept_delete_url' each.id %} " onclick="return confirm('Are you sure to delete the department?')">Delete</a>
						<a class="btn btn-primary m-1" href="{% url 'sa_dept_update_url' each.id %}">Update</a>
					</td>
				</tr>
				{% endfor %}
				
			</table>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/superadmin/sa_mentor_add.html
{% extends 'superadmin/sa_base.html' %}
{% load static %}

{% block style%}
{% endblock style%}

{% block content%}
<!-- form  -->
<div class="container p-3">
    <div class="row d-flex formdiv">
        <div class="col">
            <h4 class="pb-3">New Mentor Registration</h4>

           
            <!-- Messages -->
            {% if messages %}
            {% for message in messages %}
            
            <div class="alert alert-danger alert-dismissible fade show my-3" role="alert">
                {{message}}
                {{form1.errors}}
   
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
 
            {% endfor %}
            {% endif %}
           
            
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_email">Email Address (given by ChristUniversity)*</label>
                    {{form1.email}}
                </div>

                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label for="id_firstname">First name*</label>
                    {{form1.first_name}}
                    <!-- <input type="email" class="form-control" id="inputEmail4" placeholder="Email"> -->
                  </div>
                  <div class="form-group col-md-6">
                    <label for="id_lastname">Last name</label>
                    {{form1.last_name}}
                    <!-- <input type="email" class="form-control" id="inputEmail4" placeholder="Email"> -->
                  </div>
                </div>

                <div class="form-group">
                  <label for="id_mobile">Mobile number</label>
                  {{form1.mobile}}
                </div>
                
                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label for="id_password1">Password (min 8 characters)</label>
                    {{form1.password1}}
                  </div>
                  <div class="form-group col-md-6">
                    <label for="id_password1">Password Again</label>
                    {{form1.password2}}
                  </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="id_password1">Campus</label>
                        {{form1.campus}}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <input type="submit" class="btn btn-primary btn-block" value="Register">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="reset" class="btn btn-block btn-light">
                    </div>                               
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

templates/superadmin/sa_mentor_update.html
{% extends 'superadmin/sa_base.html' %}
{% load static %}

{% block style%}
{% endblock style%}

{% block content%}
<!-- form  -->
<div class="container p-3">
    <div class="row d-flex formdiv">
        <div class="col">
            <h4 class="pb-3">Update Mentor details</h4>

           
            <!-- Messages -->
            {% if messages %}
            {% for message in messages %}
            
            <div class="alert alert-danger alert-dismissible fade show my-3" role="alert">
                {{message}}
                {{form1.errors}}
                {{form2.errors}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
 
            {% endfor %}
            {% endif %}
           
            
            <form method="POST">
                {% csrf_token %}
                <!-- <div class="form-group disabled">
                    <label for="id_email">Email Address (given by ChristUniversity)*</label>
                    {{form1.email}}
                </div> -->

                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label for="id_firstname">First name*</label>
                    {{form1.first_name}}
                    <!-- <input type="email" class="form-control" id="inputEmail4" placeholder="Email"> -->
                  </div>
                  <div class="form-group col-md-6">
                    <label for="id_lastname">Last name</label>
                    {{form1.last_name}}
                    <!-- <input type="email" class="form-control" id="inputEmail4" placeholder="Email"> -->
                  </div>
                </div>

                <div class="form-group">
                  <label for="id_mobile">Mobile number</label>
                  {{form1.mobile}}
                </div>
                
               

                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="id_password1">Campus</label>
                        {{form1.campus}}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <input type="submit" class="btn btn-primary btn-block" value="Update">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="reset" class="btn btn-block btn-light">
                    </div>                               
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

templates/superadmin/sa_session_add.html
{% extends 'superadmin/sa_base.html' %}
{% load static %}
{% load crispy_forms_tags %}	
{% block content%}

<!-- form  -->
<div class="container p-3">
    <div class="row d-flex formdiv">
        <div class="col">
            <h4 class="pb-3">Add new Session</h4>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}

                <!-- <div class="form-group">
                    <label for="id_session">Session Name</label>
                    {{form.session|as_crispy_field}}
                </div>

                <div class="form-group">
                    <label for="id_description">Description</label>
                    {{form.description}}
                </div>

                <div class="form-group">
                    <label for="id_pic">Session Pic</label>
                    {{form.session_pic}}
                </div> -->
                
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <input type="submit" class="btn btn-primary btn-block" value="Add new session" onclick="return confirm('Are you sure to add new Session?')">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="reset" class="btn btn-block btn-light">
                    </div>                               
                </div>
            </form>
        </div>
    </div>


    <div class="container">
        <div class="row formdiv">
            <h4 class="form-header">Session List</h4>
    
            <div class="table-responsive">
            <table class="table  table-hover">
                <tr class=" text-white text-center rounded-1 tablelist" id="tablelist">
                    <th>Slno</th>
                    <th>Session</th>
                    <th>Description</th>
                    <th>Session pic path</th>
                    <th>Uploaded date</th>
                    <th>Operations</th>
                </tr>
                
    
                {% for each in temp %}
                <tr class="text-center">
                    <td>{{forloop.counter}}</td>
                    <td>{{each.session}}</td>
                    <td>{{each.description}}</td>
                    <td>{{each.session_pic}}</td>
                    <td>{{each.uploaded_date}}</td>
                    <td>
                        <a class="btn btn-danger m-1" href="{% url 'sa_session_delete_url' each.id %}" onclick="return confirm('Are you sure to Delete the Session?')">Delete</a>
                        <a class="btn btn-primary m-1" href="{% url 'sa_session_update_url' each.id %}">Update</a></td>
                    </tr>
                </tr>
                {% endfor %}
                
            </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
{% endblock %}

templates/superadmin/sa_session_list.html
{% extends 'superadmin/sa_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}


<!-- mentor List -->
<div class="container list p-3">
    <div class="row formdiv">
        {% if templist %}
        <h4 class="form-header">Session List</h4>

        <div class="table-responsive">
        <table class="table  table-hover">
            <tr class=" text-white text-center rounded-1 tablelist" id="tablelist">
                <th>Sl No</th>
                <th>Session</th>
                <th>Description</th>
                <th>Session Pic Path</th>
                <th>Uploaded date</th>
                <th>Actions</th>
            </tr>
            <tbody>
            {% for each in templist %}
                <tr>
                <td>{{forloop.counter}}</td>
                <td>{{each.session}}</td>
                <td>{{each.description}}</td>
                <td>{% if session_pic.url %} {{each.session_pic.url}} {% else %} Image path not found {% endif %}</td>
                <td>{{each.uploaded_date}}</td>
                <td>
                    <a class="btn btn-danger m-1" href="{% url 'sa_session_delete_url' each.id %}">Delete</a>
                    <a class="btn btn-primary m-1" href="{% url 'sa_session_update_url' each.id %}">Update</a></td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
        </div>

        {% else %}
        <h5>Oops! There seems to no Sessions currently</h5>
        {% endif %}
        </div>
    </div>
</div>
                
{% endblock %}

{% block script %}
{% endblock %}